--
-- PostgreSQL database dump
--

\restrict K1RM0OKeP8sHE1jwTbdWHJbWbGRohExkc2LyKnU7ZnEfb3QHBLNgQuIgZxP5GFe

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

-- Started on 2026-06-25 11:33:19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16389)
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    id bigint NOT NULL,
    admin_name character varying(255),
    email character varying(255),
    password character varying(255)
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16388)
-- Name: admins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answers (
    id bigint NOT NULL,
    feedback character varying(255),
    marks_obtained double precision,
    max_marks double precision,
    question_text character varying(255),
    student_answer text,
    updated_at timestamp(6) without time zone,
    exam_attempt_id bigint,
    question_id bigint,
    submission_id bigint
);


ALTER TABLE public.answers OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16396)
-- Name: answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 26382)
-- Name: calendar_events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.calendar_events (
    id bigint NOT NULL,
    assigned_to character varying(255),
    category character varying(255),
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    description text,
    end_datetime timestamp(6) without time zone,
    event_type character varying(255),
    priority character varying(255),
    start_datetime timestamp(6) without time zone,
    status character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    visibility character varying(255),
    shared_with text
);


ALTER TABLE public.calendar_events OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 26381)
-- Name: calendar_events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.calendar_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 17783)
-- Name: canvas_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.canvas_data (
    id bigint NOT NULL,
    canvas_image text,
    canvas_json text,
    updated_at timestamp(6) without time zone,
    answer_id bigint
);


ALTER TABLE public.canvas_data OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17782)
-- Name: canvas_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.canvas_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.canvas_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 34671)
-- Name: eligibility_audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eligibility_audit_logs (
    id bigint NOT NULL,
    file_name character varying(255),
    invalid_count integer,
    total_imported integer,
    upload_date timestamp(6) without time zone,
    uploaded_by character varying(100),
    exam_id bigint,
    exam_type character varying(20),
    last_modified_date timestamp(6) without time zone
);


ALTER TABLE public.eligibility_audit_logs OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 34670)
-- Name: eligibility_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eligibility_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eligibility_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16405)
-- Name: exam_attempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_attempts (
    id bigint NOT NULL,
    end_time timestamp(6) without time zone,
    start_time timestamp(6) without time zone,
    status character varying(255),
    exam_id bigint,
    student_enrollment_no character varying(20),
    interruption_reason character varying(255),
    is_paused boolean,
    last_active_question_id bigint,
    last_active_section integer,
    last_saved_at timestamp(6) without time zone,
    pause_count integer,
    paused_at timestamp(6) without time zone,
    remaining_time_seconds integer,
    resume_count integer,
    resumed_at timestamp(6) without time zone
);


ALTER TABLE public.exam_attempts OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16404)
-- Name: exam_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 34652)
-- Name: exam_eligibility_audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_eligibility_audit_logs (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    enrollment_no character varying(50) NOT NULL,
    exam_id bigint NOT NULL,
    exam_type character varying(20) NOT NULL,
    performed_at timestamp(6) without time zone NOT NULL,
    performed_by character varying(100),
    student_name character varying(100)
);


ALTER TABLE public.exam_eligibility_audit_logs OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 34651)
-- Name: exam_eligibility_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_eligibility_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_eligibility_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 34924)
-- Name: exam_eligible_students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_eligible_students (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    division character varying(20),
    enrollment_no character varying(50),
    exam_id bigint,
    exam_type character varying(20),
    imported_at timestamp(6) without time zone,
    imported_by character varying(100),
    roll_no character varying(20),
    student_name character varying(200),
    updated_at timestamp(6) without time zone,
    semester character varying(50),
    student_id bigint
);


ALTER TABLE public.exam_eligible_students OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 34923)
-- Name: exam_eligible_students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_eligible_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_eligible_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 26334)
-- Name: exam_paste_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_paste_logs (
    id bigint NOT NULL,
    paste_attempt character varying(255),
    question_id bigint,
    source_type character varying(255),
    student_id character varying(255),
    "time" timestamp(6) without time zone
);


ALTER TABLE public.exam_paste_logs OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 26333)
-- Name: exam_paste_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_paste_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_paste_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 26445)
-- Name: exam_violations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exam_violations (
    id bigint NOT NULL,
    event_type character varying(255) NOT NULL,
    exam_id bigint,
    exam_type character varying(255),
    student_id character varying(255) NOT NULL,
    "time" timestamp(6) without time zone NOT NULL
);


ALTER TABLE public.exam_violations OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 26444)
-- Name: exam_violations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exam_violations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_violations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16413)
-- Name: exams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams (
    id bigint NOT NULL,
    course character varying(255),
    duration_minutes integer,
    exam_name character varying(255),
    semester character varying(255),
    subject character varying(255),
    total_marks double precision,
    exam_duration integer,
    activation_time timestamp(6) without time zone,
    exam_status character varying(255),
    started_by_admin boolean,
    activated_time timestamp(6) without time zone,
    published_time timestamp(6) without time zone,
    target_semester character varying(255)
);


ALTER TABLE public.exams OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16412)
-- Name: exams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16421)
-- Name: feedbacks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.feedbacks (
    id bigint NOT NULL,
    comments text,
    exam_id bigint,
    exam_type character varying(255),
    paper_clear character varying(255),
    rating integer,
    submitted_at timestamp(6) without time zone,
    system_easy_to_use character varying(255),
    technical_issues character varying(255),
    student_enrollment_no character varying(20)
);


ALTER TABLE public.feedbacks OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16420)
-- Name: feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16429)
-- Name: papers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.papers (
    id bigint NOT NULL,
    course character varying(255),
    duration_minutes integer,
    file_path character varying(255),
    semester character varying(255),
    subject character varying(255),
    total_marks double precision,
    uploaded_at timestamp(6) without time zone,
    exam_duration integer,
    manual_content text,
    activation_time timestamp(6) without time zone,
    exam_status character varying(255),
    started_by_admin boolean,
    activated_time timestamp(6) without time zone,
    published_time timestamp(6) without time zone,
    admin_id bigint,
    reminder_minutes_before integer,
    exam_date date
);


ALTER TABLE public.papers OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16428)
-- Name: papers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.papers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.papers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16437)
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    is_optional boolean,
    is_or_option boolean,
    marks double precision,
    question_group character varying(255),
    text text,
    exam_id bigint,
    paper_id bigint,
    pair_id character varying(255)
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16436)
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16445)
-- Name: results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.results (
    id bigint NOT NULL,
    evaluated_at timestamp(6) without time zone,
    max_total_marks double precision,
    total_marks double precision,
    submission_id bigint,
    division character varying(255),
    enrollment_no character varying(255),
    obtained_marks double precision,
    semester character varying(255),
    status character varying(255),
    student_name character varying(255),
    subject character varying(255),
    exam_name character varying(255),
    result_status character varying(255),
    subject_name character varying(255),
    obtained_marks_legacy double precision,
    roll_no integer,
    grade character varying(255),
    percentage double precision,
    terminated_at timestamp(6) without time zone,
    termination_reason character varying(255)
);


ALTER TABLE public.results OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16444)
-- Name: results_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17862)
-- Name: student_active_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_active_sessions (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    last_activity timestamp(6) without time zone NOT NULL,
    login_time timestamp(6) without time zone NOT NULL,
    session_id character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL,
    browser_info character varying(255),
    device_info character varying(255),
    ip_address character varying(255),
    logout_time timestamp(6) without time zone,
    status character varying(255)
);


ALTER TABLE public.student_active_sessions OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17861)
-- Name: student_active_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_active_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_active_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 34637)
-- Name: student_exam_activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_exam_activity (
    id bigint NOT NULL,
    current_question_no integer,
    current_section character varying(255),
    exam_id bigint,
    last_activity_time timestamp(6) without time zone,
    status character varying(255),
    time_remaining character varying(255),
    updated_at timestamp(6) without time zone,
    student_id bigint NOT NULL
);


ALTER TABLE public.student_exam_activity OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 34636)
-- Name: student_exam_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_exam_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_exam_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 26437)
-- Name: student_login_attempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_login_attempts (
    id bigint NOT NULL,
    attempt_time timestamp(6) without time zone NOT NULL,
    browser_info character varying(255),
    device_info character varying(255),
    ip_address character varying(255),
    result character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL
);


ALTER TABLE public.student_login_attempts OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 26436)
-- Name: student_login_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_login_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17390)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    student_name character varying(100),
    enrollment_no character varying(20),
    division character varying(20),
    roll_no integer,
    phone_no character varying(15),
    password character varying(100),
    semester character varying(50),
    gr_no character varying(50)
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17389)
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.students_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.students_id_seq OWNER TO postgres;

--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 235
-- Name: students_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.students_id_seq OWNED BY public.students.id;


--
-- TOC entry 234 (class 1259 OID 16458)
-- Name: submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.submissions (
    id bigint NOT NULL,
    status character varying(255),
    submitted_at timestamp(6) without time zone,
    paper_id bigint,
    student_enrollment_no character varying(20),
    interruption_reason character varying(255),
    is_paused boolean,
    last_active_question_id bigint,
    last_active_section integer,
    last_saved_at timestamp(6) without time zone,
    pause_count integer,
    paused_at timestamp(6) without time zone,
    remaining_time_seconds integer,
    resume_count integer,
    resumed_at timestamp(6) without time zone
);


ALTER TABLE public.submissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16457)
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4837 (class 2604 OID 17398)
-- Name: students id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students ALTER COLUMN id SET DEFAULT nextval('public.students_id_seq'::regclass);


--
-- TOC entry 5050 (class 0 OID 16389)
-- Dependencies: 218
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (id, admin_name, email, password) FROM stdin;
3	superadmin	superadmin@ljku.edu.in	super123
4	examadmin	examadmin@ljku.edu.in	exam123
5	facultyadmin	faculty@ljku.edu.in	faculty123
6	controller	controller@ljku.edu.in	controller123
1	Nirav	admin@ljku.edu.in	admin
2	admin	admin@ljku.edu.in	admin123
\.


--
-- TOC entry 5052 (class 0 OID 16397)
-- Dependencies: 220
-- Data for Name: answers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.answers (id, feedback, marks_obtained, max_marks, question_text, student_answer, updated_at, exam_attempt_id, question_id, submission_id) FROM stdin;
\.


--
-- TOC entry 5076 (class 0 OID 26382)
-- Dependencies: 244
-- Data for Name: calendar_events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.calendar_events (id, assigned_to, category, created_at, created_by, description, end_datetime, event_type, priority, start_datetime, status, title, updated_at, visibility, shared_with) FROM stdin;
31	admin	Exam Preparation	2026-06-20 16:18:00.438384	admin	Course: BCA\nSemester: 4\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-21 11:30:00	EXAM	HIGH	2026-06-21 09:00:00	Pending	📘 DS Examination	2026-06-20 16:18:00.438384	SHARED	\N
32	admin	Exam Preparation	2026-06-20 16:19:21.486714	admin	Course: BCA\nSemester: 2\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-21 11:30:00	EXAM	HIGH	2026-06-21 09:00:00	Pending	📘 DS Examination	2026-06-20 16:19:21.486714	SHARED	\N
33	admin	Exam Preparation	2026-06-20 16:21:13.612257	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-21 11:30:00	EXAM	HIGH	2026-06-21 09:00:00	Pending	📘 DS Examination	2026-06-20 16:21:13.612257	SHARED	\N
34	admin	Exam Preparation	2026-06-22 16:52:37.833423	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-23 11:30:00	EXAM	HIGH	2026-06-23 09:00:00	Pending	📘 DS Examination	2026-06-22 16:52:37.833423	SHARED	\N
35	admin	Exam Preparation	2026-06-22 19:01:52.99412	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-23 11:30:00	EXAM	HIGH	2026-06-23 09:00:00	Pending	📘 AS Examination	2026-06-22 19:01:52.99412	SHARED	\N
36	admin	Exam Preparation	2026-06-24 10:00:42.936758	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-25 11:30:00	EXAM	HIGH	2026-06-25 09:00:00	Pending	📘 AS Examination	2026-06-24 10:00:42.936758	SHARED	\N
8	admin	admin	2026-06-14 11:03:06.678358	Nirav		2026-06-16 11:56:00	TASK	LOW	2026-06-16 10:56:00	Completed	zxvcx	2026-06-14 17:44:55.843685	SHARED	\N
11	admin	admin	2026-06-14 17:44:30.587138	admin		2026-06-14 18:43:00	TASK	LOW	2026-06-14 17:43:00	Overdue	asdadasda	2026-06-15 11:09:59.301829	PRIVATE	\N
15	admin	admin	2026-06-14 17:56:00.49899	admin		2026-06-14 18:55:00	TASK	MEDIUM	2026-06-14 17:55:00	Overdue	asasdasd	2026-06-15 11:09:59.369811	SHARED	,3,
16	admin	Exam Preparation	2026-06-15 11:12:18.559054	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 DM Examination	2026-06-15 11:12:18.559054	SHARED	\N
17	admin	Exam Preparation	2026-06-15 11:36:45.248214	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 11:36:45.248214	SHARED	\N
18	admin	Exam Preparation	2026-06-15 11:56:02.856053	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 11:56:02.856053	SHARED	\N
19	admin	Exam Preparation	2026-06-15 12:13:43.883574	admin	Course: IMCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 120 mins	2026-06-16 11:00:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 DBMS Examination	2026-06-15 12:13:43.883574	SHARED	\N
20	admin	Exam Preparation	2026-06-15 12:21:56.460234	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 12:21:56.460234	SHARED	\N
37	admin	Exam Preparation	2026-06-24 10:01:35.445331	admin	Course: BCA\nSemester: 5\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-25 11:30:00	EXAM	HIGH	2026-06-25 09:00:00	Pending	📘 DS Examination	2026-06-24 10:01:35.445331	SHARED	\N
38	admin	Exam Preparation	2026-06-24 10:11:22.216419	admin	Course: BCA\nSemester: 5\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-25 11:30:00	EXAM	HIGH	2026-06-25 09:00:00	Pending	📘 DSss Examination	2026-06-24 10:11:22.216419	SHARED	\N
12	superadmin	admin	2026-06-14 17:45:13.961786	superadmin		2026-06-14 18:45:00	TASK	LOW	2026-06-14 17:45:00	Overdue	asasdasdsad	2026-06-15 12:32:53.75037	PRIVATE	\N
21	superadmin	Exam Preparation	2026-06-15 12:47:46.922627	superadmin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 12:47:46.922627	SHARED	\N
22	superadmin	Exam Preparation	2026-06-15 12:48:35.789754	superadmin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 12:48:35.789754	SHARED	\N
14	superadmin	admin	2026-06-14 17:53:59.037264	admin		2026-06-15 18:53:00	TASK	LOW	2026-06-15 17:53:00	Overdue	asdasdasd	2026-06-15 20:50:28.095937	SHARED	
23	admin	Exam Preparation	2026-06-15 20:52:18.914407	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 20:52:18.914407	SHARED	\N
24	admin	Exam Preparation	2026-06-15 21:04:57.698604	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 C Examination	2026-06-15 21:04:57.698604	SHARED	\N
25	admin	Exam Preparation	2026-06-15 21:58:06.462455	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 DS Examination	2026-06-15 21:58:06.462455	SHARED	\N
26	admin	Exam Preparation	2026-06-15 22:12:11.588036	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-16 11:30:00	EXAM	HIGH	2026-06-16 09:00:00	Pending	📘 DS Examination	2026-06-15 22:12:11.588036	SHARED	\N
27	admin	Exam Preparation	2026-06-19 09:34:08.277147	admin	Course: BCA\nSemester: 5\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-20 11:30:00	EXAM	HIGH	2026-06-20 09:00:00	Pending	📘 DS Examination	2026-06-19 09:34:08.277147	SHARED	\N
28	admin	Exam Preparation	2026-06-19 09:42:27.632914	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-20 11:30:00	EXAM	HIGH	2026-06-20 09:00:00	Pending	📘 DS Examination	2026-06-19 09:42:27.632914	SHARED	\N
29	admin	Exam Preparation	2026-06-19 20:13:45.648978	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-20 11:30:00	EXAM	HIGH	2026-06-20 09:00:00	Pending	📘 DS Examination	2026-06-19 20:13:45.648978	SHARED	\N
30	admin	Exam Preparation	2026-06-20 10:52:27.379751	admin	Course: BCA\nSemester: 3\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-21 11:30:00	EXAM	HIGH	2026-06-21 09:00:00	Pending	📘 DS Examination	2026-06-20 10:52:27.379751	SHARED	\N
39	admin	Exam Preparation	2026-06-24 17:53:56.116458	admin	Course: BCA\nSemester: 5\nTotal Marks: 50.0\nDuration: 150 mins	2026-06-25 11:30:00	EXAM	HIGH	2026-06-25 09:00:00	Pending	📘 DS Examination	2026-06-24 17:53:56.116458	SHARED	\N
\.


--
-- TOC entry 5070 (class 0 OID 17783)
-- Dependencies: 238
-- Data for Name: canvas_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.canvas_data (id, canvas_image, canvas_json, updated_at, answer_id) FROM stdin;
\.


--
-- TOC entry 5086 (class 0 OID 34671)
-- Dependencies: 254
-- Data for Name: eligibility_audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.eligibility_audit_logs (id, file_name, invalid_count, total_imported, upload_date, uploaded_by, exam_id, exam_type, last_modified_date) FROM stdin;
1	students_list.pdf	0	3	2026-06-22 16:56:30.223906	admin	\N	\N	\N
2	BS-R-Lab.pdf	0	431	2026-06-22 19:02:04.14773	admin	2	PAPER	2026-06-22 19:02:04.14773
3	Semester5_Student_List.pdf	0	5	2026-06-24 10:02:06.334554	admin	2	PAPER	2026-06-24 10:02:06.334554
4	Semester5_Student_List.pdf	0	5	2026-06-24 10:13:43.23103	admin	3	PAPER	2026-06-24 10:13:43.23103
5	Semester5_Student_List.pdf	0	5	2026-06-24 17:54:13.266512	admin	1	PAPER	2026-06-24 17:54:13.266512
\.


--
-- TOC entry 5054 (class 0 OID 16405)
-- Dependencies: 222
-- Data for Name: exam_attempts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_attempts (id, end_time, start_time, status, exam_id, student_enrollment_no, interruption_reason, is_paused, last_active_question_id, last_active_section, last_saved_at, pause_count, paused_at, remaining_time_seconds, resume_count, resumed_at) FROM stdin;
\.


--
-- TOC entry 5084 (class 0 OID 34652)
-- Dependencies: 252
-- Data for Name: exam_eligibility_audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_eligibility_audit_logs (id, action, enrollment_no, exam_id, exam_type, performed_at, performed_by, student_name) FROM stdin;
\.


--
-- TOC entry 5088 (class 0 OID 34924)
-- Dependencies: 256
-- Data for Name: exam_eligible_students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_eligible_students (id, created_at, division, enrollment_no, exam_id, exam_type, imported_at, imported_by, roll_no, student_name, updated_at, semester, student_id) FROM stdin;
1	2026-06-24 17:54:13.269481	A	2400450121070	1	PAPER	2026-06-24 17:54:13.266512	admin		Rohan Patel	2026-06-24 17:54:13.269481	Semester 5	1
2	2026-06-24 17:54:13.272503	A	2400450121071	1	PAPER	2026-06-24 17:54:13.266512	admin		Sneha Shah	2026-06-24 17:54:13.272503	Semester 5	2
3	2026-06-24 17:54:13.274483	B	2400450121072	1	PAPER	2026-06-24 17:54:13.266512	admin		Jay Mehta	2026-06-24 17:54:13.274483	Semester 5	3
4	2026-06-24 17:54:13.276014	B	2400450121073	1	PAPER	2026-06-24 17:54:13.266512	admin		Khushi Patel	2026-06-24 17:54:13.276014	Semester 5	4
5	2026-06-24 17:54:13.279037	B	2400450121080	1	PAPER	2026-06-24 17:54:13.266512	admin		Nisarg Shah	2026-06-24 17:54:13.279037	Semester 5	5
\.


--
-- TOC entry 5074 (class 0 OID 26334)
-- Dependencies: 242
-- Data for Name: exam_paste_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_paste_logs (id, paste_attempt, question_id, source_type, student_id, "time") FROM stdin;
1	Internal Paste Allowed	259	INTERNAL_EXAM	24004501210261	2026-06-07 10:02:57.722427
2	External Paste Attempt blocked	259	EXTERNAL	24004501210261	2026-06-07 10:03:06.885854
3	External Paste Attempt blocked	259	EXTERNAL	24004501210261	2026-06-07 10:03:15.792174
4	External Paste Attempt blocked	259	EXTERNAL	24004501210261	2026-06-07 10:03:22.241193
5	External Paste Attempt blocked	259	EXTERNAL	24004501210261	2026-06-07 10:04:21.856036
6	Internal Paste Allowed	259	INTERNAL_EXAM	24004501210261	2026-06-07 10:04:25.642986
7	Internal Paste Allowed	259	INTERNAL_EXAM	24004501210261	2026-06-07 10:04:28.782996
8	Internal Paste Allowed	259	INTERNAL_EXAM	24004501210261	2026-06-07 10:04:45.148201
\.


--
-- TOC entry 5080 (class 0 OID 26445)
-- Dependencies: 248
-- Data for Name: exam_violations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exam_violations (id, event_type, exam_id, exam_type, student_id, "time") FROM stdin;
1	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:42:55.45447
2	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:42:59.220893
3	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:00.1497
4	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:01.368223
5	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:04.915803
6	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:28.96446
7	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:30.874847
8	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:37.270815
9	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:43:39.18301
10	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:48:12.824213
11	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:48:17.00727
12	TAB_SWITCH	6	paper	24004501210260	2026-06-19 09:48:44.483866
13	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:14:10.572588
14	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:14:12.233185
15	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:14:31.496968
16	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:15:21.060024
17	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:15:29.523445
18	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:15:43.357663
19	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:28:29.250163
20	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:28:32.354848
21	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:28:36.353334
22	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:28:40.274123
23	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:28:55.936014
24	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:28:58.987101
25	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:28:59.201641
26	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:29:06.720443
27	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:29:07.214863
28	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:29:28.524343
29	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:29:29.239447
30	TAB_SWITCH	7	paper	24004501210260	2026-06-19 20:30:43.531879
31	FOCUS_LOST	7	paper	24004501210260	2026-06-19 20:30:44.230921
32	TAB_SWITCH	12	paper	24004501210260	2026-06-20 16:21:38.059836
33	FOCUS_LOST	12	paper	24004501210260	2026-06-20 16:28:03.817146
34	TAB_SWITCH	12	paper	24004501210260	2026-06-20 16:28:11.774739
35	FOCUS_LOST	12	paper	24004501210260	2026-06-20 16:28:12.563136
36	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:05.56955
37	FOCUS_LOST	2	paper	2400450121070	2026-06-24 10:03:06.50481
38	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:19.499927
39	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:22.043279
40	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:24.687496
41	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:27.029113
42	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:28.532786
43	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:29.823916
44	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:03:32.191639
45	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:04:29.347096
46	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:04:35.192201
47	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:04:41.50915
48	TAB_SWITCH	2	paper	2400450121070	2026-06-24 10:04:52.603491
49	TAB_SWITCH	2	paper	2400450121071	2026-06-24 10:05:18.685177
50	FOCUS_LOST	2	paper	2400450121071	2026-06-24 10:05:20.53388
\.


--
-- TOC entry 5056 (class 0 OID 16413)
-- Dependencies: 224
-- Data for Name: exams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exams (id, course, duration_minutes, exam_name, semester, subject, total_marks, exam_duration, activation_time, exam_status, started_by_admin, activated_time, published_time, target_semester) FROM stdin;
\.


--
-- TOC entry 5058 (class 0 OID 16421)
-- Dependencies: 226
-- Data for Name: feedbacks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.feedbacks (id, comments, exam_id, exam_type, paper_clear, rating, submitted_at, system_easy_to_use, technical_issues, student_enrollment_no) FROM stdin;
1	adasdasds	2	paper	\N	5	2026-06-24 10:05:31.331391	\N	\N	2400450121071
2	khluyutreawSZD	2	paper	\N	5	2026-06-24 10:08:59.386645	\N	\N	2400450121070
\.


--
-- TOC entry 5060 (class 0 OID 16429)
-- Dependencies: 228
-- Data for Name: papers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.papers (id, course, duration_minutes, file_path, semester, subject, total_marks, uploaded_at, exam_duration, manual_content, activation_time, exam_status, started_by_admin, activated_time, published_time, admin_id, reminder_minutes_before, exam_date) FROM stdin;
1	BCA	\N	/uploads/de2c5e05-2ace-439b-a718-51f745c0db97.pdf	5	DS	50	2026-06-24 17:53:53.122598	150	\N	\N	PUBLISHED	\N	\N	2026-06-24 17:53:56.069877	2	\N	2026-06-24
\.


--
-- TOC entry 5062 (class 0 OID 16437)
-- Dependencies: 230
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questions (id, is_optional, is_or_option, marks, question_group, text, exam_id, paper_id, pair_id) FROM stdin;
1	f	f	1	Q1	1. Give any two examples of data structure.	\N	1	
2	f	f	1	Q1	2. What is the difference between static and dynamic memory allocation?	\N	1	
3	f	f	1	Q1	3. Write the time complexity of linear search in best and worst case	\N	1	
4	f	f	3	Q1	4. Explain any two applications of stacks in real-life programming.	\N	1	
5	t	t	4	Q1	5. Explain array implementation of push and pop operations on stack.	\N	1	P1
6	t	t	4	Q1	5. Write a brief note on analysis of algorithm.	\N	1	P1
7	f	f	1	Q2	1. What is priority queue?	\N	1	
8	f	f	1	Q2	2. What is the role of front and rear in queue implementation?	\N	1	
9	f	f	1	Q2	3. What is sparse matrix?	\N	1	
10	f	f	3	Q2	4. Explain collision with example.	\N	1	
11	t	t	4	Q2	5. Write an algorithm to insert and delete elements from a circular queue	\N	1	P2
12	t	t	4	Q2	5. Write an algorithm to insert and delete elements from a simple queue	\N	1	P2
13	f	f	1	Q3	1. What is a linked list?	\N	1	
14	f	f	1	Q3	2. What is the difference between singly and doubly linked lists?	\N	1	
15	f	f	1	Q3	3. Write any one application of doubly linked list.	\N	1	
16	f	f	3	Q3	4. Compare array and linked list.	\N	1	
17	t	t	4	Q3	5. Write an algorithm to insert a node at the beginning of a singly linked list.	\N	1	P3
18	t	t	4	Q3	5. Write an algorithm to insert a node at the beginning of a doubly linked list.	\N	1	P3
19	f	f	1	Q4	1. What is a binary tree?	\N	1	
20	f	f	1	Q4	2. What is the difference between complete and full binary trees?	\N	1	
21	f	f	1	Q4	3. List any two tree traversal technique.	\N	1	
22	f	f	3	Q4	4. Construct a binary search tree using following values: 30, 10, 50, 5, 20, 2	\N	1	
23	t	t	4	Q4	5. Write and explain in-order, pre-order and post-order traversal of a binary tree.	\N	1	P4
24	t	t	4	Q4	5. Explain creation of 2-3 tree with suitable example.	\N	1	P4
25	f	f	1	Q5	1. Define adjacency matrix with an example	\N	1	
26	f	f	1	Q5	2. Write exactly one difference between tree and graph	\N	1	
27	f	f	1	Q5	3. What is the difference between BFS and DFS?	\N	1	
28	f	f	3	Q5	4. Explain Kruskal’s algorithm for finding minimum spanning tree with suitable example.	\N	1	
29	t	t	4	Q5	5. Explain Dijkstra’s algorithm with example for shortest path.	\N	1	P5
30	t	t	4	Q5	5. Write an algorithm for Breadth-First Search (BFS) traversal.	\N	1	P5
\.


--
-- TOC entry 5064 (class 0 OID 16445)
-- Dependencies: 232
-- Data for Name: results; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.results (id, evaluated_at, max_total_marks, total_marks, submission_id, division, enrollment_no, obtained_marks, semester, status, student_name, subject, exam_name, result_status, subject_name, obtained_marks_legacy, roll_no, grade, percentage, terminated_at, termination_reason) FROM stdin;
\.


--
-- TOC entry 5072 (class 0 OID 17862)
-- Dependencies: 240
-- Data for Name: student_active_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_active_sessions (id, is_active, last_activity, login_time, session_id, student_id, browser_info, device_info, ip_address, logout_time, status) FROM stdin;
\.


--
-- TOC entry 5082 (class 0 OID 34637)
-- Dependencies: 250
-- Data for Name: student_exam_activity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_exam_activity (id, current_question_no, current_section, exam_id, last_activity_time, status, time_remaining, updated_at, student_id) FROM stdin;
2	6	Q5	2	2026-06-24 10:05:31.34726	Submitted	00:00:00	2026-06-24 10:05:31.34726	2
1	6	Q5	2	2026-06-24 10:08:59.398648	Active	02:27:07	2026-06-24 10:08:59.398648	1
\.


--
-- TOC entry 5078 (class 0 OID 26437)
-- Dependencies: 246
-- Data for Name: student_login_attempts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_login_attempts (id, attempt_time, browser_info, device_info, ip_address, result, student_id) FROM stdin;
1	2026-06-16 09:54:48.506127	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
2	2026-06-16 09:55:14.424276	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
3	2026-06-16 09:55:19.200097	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
4	2026-06-16 09:55:41.348914	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
5	2026-06-16 09:55:53.537292	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
6	2026-06-16 09:57:44.556857	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
7	2026-06-16 09:58:07.697193	Edge	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
8	2026-06-19 09:34:26.721832	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
9	2026-06-19 09:34:42.386925	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
10	2026-06-19 09:35:25.649303	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210261
11	2026-06-19 09:42:35.868314	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
12	2026-06-19 09:48:03.275581	Chrome	Windows PC	127.0.0.1	SUCCESS	24004501210260
13	2026-06-19 20:14:01.161136	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
14	2026-06-20 10:51:38.9143	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
15	2026-06-20 16:18:18.020768	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
16	2026-06-20 16:18:46.786558	Chrome	Windows PC	127.0.0.1	BLOCKED	24004501210260
17	2026-06-20 16:19:31.457826	Chrome	Windows PC	127.0.0.1	BLOCKED	24004501210260
18	2026-06-20 16:19:58.890613	Chrome	Windows PC	127.0.0.1	SUCCESS	24004501210261
19	2026-06-20 16:20:37.235889	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
20	2026-06-22 16:57:27.083274	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	24004501210260
21	2026-06-22 17:10:14.310717	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210261
22	2026-06-22 19:16:18.357814	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	24004501210260
23	2026-06-24 10:02:51.913115	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	2400450121070
24	2026-06-24 10:04:20.391424	Chrome	Windows PC	0:0:0:0:0:0:0:1	SUCCESS	2400450121071
25	2026-06-24 10:14:40.020096	Chrome	Windows PC	0:0:0:0:0:0:0:1	BLOCKED	2400450121070
\.


--
-- TOC entry 5068 (class 0 OID 17390)
-- Dependencies: 236
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.students (id, student_name, enrollment_no, division, roll_no, phone_no, password, semester, gr_no) FROM stdin;
1	Rohan Patel	2400450121070	A	34	9876500001	5701070	Semester 5	GR2025070
2	Sneha Shah	2400450121071	A	35	9876500002	5701071	Semester 5	GR2025071
3	Jay Mehta	2400450121072	B	23	9876500003	5701072	Semester 5	GR2025072
4	Khushi Patel	2400450121073	B	24	9876500004	5701073	Semester 5	GR2025073
5	Nisarg Shah	2400450121080	B	25	9876500011	5701080	Semester 5	GR2025080
\.


--
-- TOC entry 5066 (class 0 OID 16458)
-- Dependencies: 234
-- Data for Name: submissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.submissions (id, status, submitted_at, paper_id, student_enrollment_no, interruption_reason, is_paused, last_active_question_id, last_active_section, last_saved_at, pause_count, paused_at, remaining_time_seconds, resume_count, resumed_at) FROM stdin;
\.


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 217
-- Name: admins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admins_id_seq', 6, true);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 219
-- Name: answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.answers_id_seq', 1, false);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 243
-- Name: calendar_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.calendar_events_id_seq', 39, true);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 237
-- Name: canvas_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.canvas_data_id_seq', 1, false);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 253
-- Name: eligibility_audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.eligibility_audit_logs_id_seq', 5, true);


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 221
-- Name: exam_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_attempts_id_seq', 1, false);


--
-- TOC entry 5101 (class 0 OID 0)
-- Dependencies: 251
-- Name: exam_eligibility_audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_eligibility_audit_logs_id_seq', 1, false);


--
-- TOC entry 5102 (class 0 OID 0)
-- Dependencies: 255
-- Name: exam_eligible_students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_eligible_students_id_seq', 5, true);


--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 241
-- Name: exam_paste_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_paste_logs_id_seq', 8, true);


--
-- TOC entry 5104 (class 0 OID 0)
-- Dependencies: 247
-- Name: exam_violations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exam_violations_id_seq', 50, true);


--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 223
-- Name: exams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exams_id_seq', 1, false);


--
-- TOC entry 5106 (class 0 OID 0)
-- Dependencies: 225
-- Name: feedbacks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.feedbacks_id_seq', 2, true);


--
-- TOC entry 5107 (class 0 OID 0)
-- Dependencies: 227
-- Name: papers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.papers_id_seq', 1, true);


--
-- TOC entry 5108 (class 0 OID 0)
-- Dependencies: 229
-- Name: questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.questions_id_seq', 30, true);


--
-- TOC entry 5109 (class 0 OID 0)
-- Dependencies: 231
-- Name: results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.results_id_seq', 1, false);


--
-- TOC entry 5110 (class 0 OID 0)
-- Dependencies: 239
-- Name: student_active_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_active_sessions_id_seq', 150, true);


--
-- TOC entry 5111 (class 0 OID 0)
-- Dependencies: 249
-- Name: student_exam_activity_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_exam_activity_id_seq', 2, true);


--
-- TOC entry 5112 (class 0 OID 0)
-- Dependencies: 245
-- Name: student_login_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_login_attempts_id_seq', 25, true);


--
-- TOC entry 5113 (class 0 OID 0)
-- Dependencies: 235
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_id_seq', 5, true);


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 233
-- Name: submissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.submissions_id_seq', 1, false);


--
-- TOC entry 4839 (class 2606 OID 16395)
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- TOC entry 4841 (class 2606 OID 16403)
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_pkey PRIMARY KEY (id);


--
-- TOC entry 4877 (class 2606 OID 26388)
-- Name: calendar_events calendar_events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_events
    ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);


--
-- TOC entry 4867 (class 2606 OID 17789)
-- Name: canvas_data canvas_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.canvas_data
    ADD CONSTRAINT canvas_data_pkey PRIMARY KEY (id);


--
-- TOC entry 4887 (class 2606 OID 34675)
-- Name: eligibility_audit_logs eligibility_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eligibility_audit_logs
    ADD CONSTRAINT eligibility_audit_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4847 (class 2606 OID 16411)
-- Name: exam_attempts exam_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT exam_attempts_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 34656)
-- Name: exam_eligibility_audit_logs exam_eligibility_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_eligibility_audit_logs
    ADD CONSTRAINT exam_eligibility_audit_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 34928)
-- Name: exam_eligible_students exam_eligible_students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_eligible_students
    ADD CONSTRAINT exam_eligible_students_pkey PRIMARY KEY (id);


--
-- TOC entry 4875 (class 2606 OID 26340)
-- Name: exam_paste_logs exam_paste_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_paste_logs
    ADD CONSTRAINT exam_paste_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4881 (class 2606 OID 26451)
-- Name: exam_violations exam_violations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_violations
    ADD CONSTRAINT exam_violations_pkey PRIMARY KEY (id);


--
-- TOC entry 4849 (class 2606 OID 16419)
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);


--
-- TOC entry 4851 (class 2606 OID 16427)
-- Name: feedbacks feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT feedbacks_pkey PRIMARY KEY (id);


--
-- TOC entry 4853 (class 2606 OID 16435)
-- Name: papers papers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.papers
    ADD CONSTRAINT papers_pkey PRIMARY KEY (id);


--
-- TOC entry 4855 (class 2606 OID 16443)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- TOC entry 4857 (class 2606 OID 16449)
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 17868)
-- Name: student_active_sessions student_active_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_active_sessions
    ADD CONSTRAINT student_active_sessions_pkey PRIMARY KEY (id);


--
-- TOC entry 4883 (class 2606 OID 34643)
-- Name: student_exam_activity student_exam_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_exam_activity
    ADD CONSTRAINT student_exam_activity_pkey PRIMARY KEY (id);


--
-- TOC entry 4879 (class 2606 OID 26443)
-- Name: student_login_attempts student_login_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_login_attempts
    ADD CONSTRAINT student_login_attempts_pkey PRIMARY KEY (id);


--
-- TOC entry 4863 (class 2606 OID 17397)
-- Name: students students_enrollment_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_enrollment_no_key UNIQUE (enrollment_no);


--
-- TOC entry 4865 (class 2606 OID 17400)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 4861 (class 2606 OID 16464)
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4859 (class 2606 OID 16466)
-- Name: results uk2eguybekkruujxjxi1j15lyj7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT uk2eguybekkruujxjxi1j15lyj7 UNIQUE (submission_id);


--
-- TOC entry 4869 (class 2606 OID 17791)
-- Name: canvas_data ukclfhm63o9ivv2yatguce3as8k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.canvas_data
    ADD CONSTRAINT ukclfhm63o9ivv2yatguce3as8k UNIQUE (answer_id);


--
-- TOC entry 4843 (class 2606 OID 16834)
-- Name: answers ukfkkcchecx5s7galevqlm8kda8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT ukfkkcchecx5s7galevqlm8kda8 UNIQUE (submission_id, question_id);


--
-- TOC entry 4873 (class 2606 OID 17870)
-- Name: student_active_sessions ukgn3phybd8qi2jckhhkijvdj1w; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_active_sessions
    ADD CONSTRAINT ukgn3phybd8qi2jckhhkijvdj1w UNIQUE (session_id);


--
-- TOC entry 4845 (class 2606 OID 16525)
-- Name: answers uksifxw1fuljyagm2ip7otid6b5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT uksifxw1fuljyagm2ip7otid6b5 UNIQUE (exam_attempt_id, question_id);


--
-- TOC entry 4903 (class 2606 OID 34644)
-- Name: student_exam_activity fk116aylddcldknkt1mebr1u1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_exam_activity
    ADD CONSTRAINT fk116aylddcldknkt1mebr1u1w FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- TOC entry 4902 (class 2606 OID 17792)
-- Name: canvas_data fk1j4su6dxam1c9fg0fmgyxi6kt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.canvas_data
    ADD CONSTRAINT fk1j4su6dxam1c9fg0fmgyxi6kt FOREIGN KEY (answer_id) REFERENCES public.answers(id);


--
-- TOC entry 4895 (class 2606 OID 17421)
-- Name: feedbacks fk2kfhqwpdqpmho6ytxpi06vmy2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.feedbacks
    ADD CONSTRAINT fk2kfhqwpdqpmho6ytxpi06vmy2 FOREIGN KEY (student_enrollment_no) REFERENCES public.students(enrollment_no);


--
-- TOC entry 4890 (class 2606 OID 16472)
-- Name: answers fk3erw1a3t0r78st8ty27x6v3g1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT fk3erw1a3t0r78st8ty27x6v3g1 FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- TOC entry 4893 (class 2606 OID 17406)
-- Name: exam_attempts fk4dffubj1w141xdgb5l828wcu5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT fk4dffubj1w141xdgb5l828wcu5 FOREIGN KEY (student_enrollment_no) REFERENCES public.students(enrollment_no);


--
-- TOC entry 4896 (class 2606 OID 18514)
-- Name: papers fk4jgrc9siixsp74yfaljv54kwb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.papers
    ADD CONSTRAINT fk4jgrc9siixsp74yfaljv54kwb FOREIGN KEY (admin_id) REFERENCES public.admins(id);


--
-- TOC entry 4894 (class 2606 OID 16482)
-- Name: exam_attempts fk5tomiinihc09ywy0wh15pi2cs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT fk5tomiinihc09ywy0wh15pi2cs FOREIGN KEY (exam_id) REFERENCES public.exams(id);


--
-- TOC entry 4900 (class 2606 OID 17426)
-- Name: submissions fk60tgwxviid5gvo1524t6jo2l1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk60tgwxviid5gvo1524t6jo2l1 FOREIGN KEY (student_enrollment_no) REFERENCES public.students(enrollment_no);


--
-- TOC entry 4899 (class 2606 OID 16507)
-- Name: results fkblwh3w4ts9w5wgs122muuq281; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT fkblwh3w4ts9w5wgs122muuq281 FOREIGN KEY (submission_id) REFERENCES public.submissions(id);


--
-- TOC entry 4901 (class 2606 OID 16512)
-- Name: submissions fkcq12qvon0tfhtd3s3poi0ncpg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkcq12qvon0tfhtd3s3poi0ncpg FOREIGN KEY (paper_id) REFERENCES public.papers(id);


--
-- TOC entry 4891 (class 2606 OID 16467)
-- Name: answers fkgxrkjl0rlw2640nnk5gkny8xa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT fkgxrkjl0rlw2640nnk5gkny8xa FOREIGN KEY (exam_attempt_id) REFERENCES public.exam_attempts(id);


--
-- TOC entry 4897 (class 2606 OID 16502)
-- Name: questions fkna8isjhyhrtcvxyty4ilumfi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkna8isjhyhrtcvxyty4ilumfi FOREIGN KEY (paper_id) REFERENCES public.papers(id);


--
-- TOC entry 4892 (class 2606 OID 16477)
-- Name: answers fkrg2tg6244faytkhlsemsmrwe0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT fkrg2tg6244faytkhlsemsmrwe0 FOREIGN KEY (submission_id) REFERENCES public.submissions(id);


--
-- TOC entry 4898 (class 2606 OID 16497)
-- Name: questions fkrk78bmt53fns7np8casqa3q44; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkrk78bmt53fns7np8casqa3q44 FOREIGN KEY (exam_id) REFERENCES public.exams(id);


-- Completed on 2026-06-25 11:33:19

--
-- PostgreSQL database dump complete
--

\unrestrict K1RM0OKeP8sHE1jwTbdWHJbWbGRohExkc2LyKnU7ZnEfb3QHBLNgQuIgZxP5GFe

